service:
  name: petclinic
  identifier: petclinice
  orgIdentifier: default
  projectIdentifier: default_project
  serviceDefinition:
    spec:
      manifests:
        - manifest:
            identifier: petclinic
            type: K8sManifest
            spec:
              store:
                type: Github
                spec:
                  connectorRef: petclinic
                  gitFetchType: Branch
                  paths:
                    - k8s/
                  branch: main
              skipResourceVersioning: false
              enableDeclarativeRollback: false
    type: Kubernetes
